### ISSUE TITLE
Add `apb broker install` command

### ISSUE THREAD

**Issue by dymurray** [automationbroker/apb#121]
Since the broker requires elevated permissions to install, it might be useful for us to automate the creation of a clusterrolebinding which will allow the service account the APB is launched with to have the proper permissions. We can also mimic what we do with the recommended instructions using an API wrapper around `oc create install.yml` which creates a Kubernetes Job.

If we do this we will also prompt the user for params to pass along in the job creation task.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
