### ISSUE TITLE
Add `--registry` for `--refresh`

### ISSUE THREAD

**Issue by vpavlin** [automationbroker/apb#124]
Current behaviour:

`apb bundle list --refresh`

Refreshes all registries - which might take a while if you have even just couple added.

Desired behaviour

`apb bundle list --refresh --registry vpavlin`

I'd like to be able to specify a registry to refresh, which would allow me only refresh registry which I am working with.

Another way to do this would be to add `--refresh` to  `apb registry` as a subcomand as that is actually where I originally looked for it

**Comment by jmrodri** [comment]
@vpavlin thank you for submitting this issue. The apb tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
