### ISSUE TITLE
Some ASB bundles such as postgresql db are blacklisted

### ISSUE THREAD

**Issue by cmoulliard** [automationbroker/apb#134]
### Issue
I have installed ASB on origin 3.10 and some bundles such as `postgresql` db are blacklisted
when we use `release-1.2` of ASB

### Results

- Log of ASB
```
time="2018-09-11T05:28:21Z" level=info msg="Bundles filtered by white/blacklist filter:
\t-> openshift/dotnet\n\t-> openshift/dotnet-runtime\n\t-> openshift/httpd
\t-> openshift/jenkins\n\t-> openshift/mariadb\n\t-> openshift/mongodb
\t-> openshift/mysql\n\t-> openshift/nginx\n\t-> openshift/nodejs
\t-> openshift/perl\n\t-> openshift/php\n\t-> openshift/postgresql
\t-> openshift/python\n\t-> openshift/redis\n\t-> openshift/ruby
\t-> openshift/wildfly\n"
```

- Catalog query
```
odo catalog list services | grep dh-p
- dh-pyzip-demo-apb
- dh-proxy-config-apb
- dh-pyzip-demo-db-apb
- dh-prometheus-apb
```

snowdrop/openshift-infra#104

**Comment by jmrodri** [comment]
@cmoulliard thank you for submitting this issue. The apb tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
