### ISSUE TITLE
Spec [ postgresql-apb ] failed validation for the following reason: [ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]

### ISSUE THREAD

**Issue by cmoulliard** [automationbroker/apb#135]
With the latest image of ASB / OAB  Broker deployed on origin 3.10 using command "oc cluster add automation-service-broker", we can't use anymore some services such as `postgresql-apb` as there is a spec validation error

```
time="2018-09-11T09:14:08Z" level=warning
msg="Spec [ postgresql-apb ] failed validation for the following reason: 
[ APB Spec version [1.0.0] out of bounds 1.0 <= 1.0 ]. 
It will not be made available."
```

Broker log : https://gist.github.com/cmoulliard/789b36c015f927f66a8ec4d1c58400d0#file-gistfile1-txt-L379

**Comment by jmontleon** [comment]
This issue is on the wrong repo. It should be against ansible-service-broker. I'm going to close this and reopen it there.
