### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Asgoret** [automationbroker/apb#145]
Hi!
Where i can read full documentation about all access variables in APB? Something like java.doc. 
For example: I have local image and want add it to metadata in `apb.yml`. So where i can read about all variables?

**Comment by jmrodri** [comment]
@Asgoret thank you for submitting this issue. The apb tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
