### ISSUE TITLE
Cannot print version without kubeconfig

### ISSUE THREAD

**Issue by SamyCoenen** [automationbroker/apb#151]
To print the apb version, a kubeconfig file is required.

`apb version`

```
ERRO Error loading kubeconfig from [/root/.kube/config]: stat /root/.kube/config: no such file or directory (Try setting the kubeconfig path with -k, --kubeconfig) 
```

The temporary solution is to create an empty file and point to it with the `--kubeconfig` parameter.
```
sh-4.2# touch test
sh-4.2# apb version --kubeconfig test
apb-2.0.3
```

**Comment by jmrodri** [comment]
@SamyCoenen thank you for submitting this issue. The apb tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
