### ISSUE TITLE
[RFE] Use a TUI library to make a ncurses-like UI

### ISSUE THREAD

**Issue by jmrodri** [automationbroker/apb#44]
We could also add an actual TUI using termbox: https://github.com/nsf/termbox-go

I'm thinking instead of a line by line prompting, we could actually display a box with parameters. In addition to the stock line by line, but if it's abstracted out the CLI will only know to "displayBundle" or "displayParameter" and let abstraction decide how to call fmt.Println or termbox.displayBox(...) etc.

gocui (built on top of termbox)  https://github.com/jroimartin/gocui
dry https://github.com/moncho/dry

**Comment by dymurray** [comment]
Yeah I like this idea a lot. This will help when we have long param lists and also can help prevent a user from supplying bad input.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
