### ISSUE TITLE
Add ability to tail bundle logs to apb

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#46]
Would be convenient if the user could run `sbcli bundle provision foo-apb -f` or `sbcli bundle provision foo-apb --follow` and see the logs that result from the APB action selected.

Would be ideal to not rely on `oc` for this, so a place to start looking might be the `watch_bundle.go` code used for extracting credentials in bundle-lib.
https://github.com/automationbroker/bundle-lib/blob/master/runtime/watch_bundle.go

**Comment by jmrodri** [comment]
This sounds super useful as long as I can also CTRL-C and disconnect from it. I might want to see it start but then drop the connection but let it finish deploying.

**Comment by djwhatle** [comment]
Found a curl command that lets me do this:

`curl -XGET -H "Content-type: application/json" -H "Authorization: Bearer <REDACTED>" 'https://<hostname>:8443/api/v1/namespaces/openshift-apiserver/pods/openshift-apiserver-vm852/log?follow=true' -k`

Haven't been able to find any support for tailing logs in client-go. Haven't yet figured exactly out how `oc` log tailing gets called, but looks like it tacks some additional features on top of the kubectl log command.

https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/logs.go

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/logs.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/util/logs/logs.go

**Comment by djwhatle** [comment]
Closed via https://github.com/automationbroker/apb/pull/76
