### ISSUE TITLE
Suggest adding the ansibleplaybookbundle registry on first run

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#50]
Currently, `sbcli bundle list` (or any other command) shows a message on first run:

```
WARN Didn't find config file, creating one.   
```
To give people an easier getting started experience, we could emit a message telling users how to add their first registry (ansibleplaybookbundle).

My suggestion is that we add a warning that displays whenever no registries are found telling users how to get their first registry configured. The new startup might look something like this:

```
WARN Didn't find config file, creating one.   
WARN No registries configured, use "sbcli registry add" to add a registry.
```

In this case, it's pretty nice that the simple command `sbcli registry add` has defaults to get you the ansibleplaybookbundle registry without supplying further options.

We might not want to nag users about this if they're just trying to perform a build command, but for commands that definitely won't work without a registry configured, I suggest we emit this warning every time.

**Comment by dymurray** [comment]
I think this has been fixed now yes?

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
