### ISSUE TITLE
Add "apb catalog relist". Document needed permissions

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#56]

**Comment by dymurray** [comment]
Thinking we should support:
```
$ sbcli broker bootstrap
$ sbcli broker catalog/list
$ sbcli catalog relist
```

**Comment by djwhatle** [comment]
@dymurray agree. It would be great if we could provide informative help text for each of these commands. They're pretty jargony when you're first starting to work with the catalog and brokers, so a basic literal description of what's happening could go a long way.

**Comment by djwhatle** [comment]
`broker catalog` and `broker bootstrap` were implemented in https://github.com/automationbroker/sbcli/pull/63

@dymurray are you still thinking of adding relist?

**Comment by djwhatle** [comment]
We still don't have a fine-grained permission list for these actions. Currently the `apb` tool recommends adding cluster-admin to a user to run `broker bootstrap/catalog` and `catalog relist`.
