### ISSUE TITLE
Detect available namespaces when listing bundles from local OpenShift registry

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#77]
Goal is to prevent user from having to manually make additions to ~/.apb.json config file when they build bundle images in a new namespace.

**Comment by djwhatle** [comment]
Need to investigate if we would make this change within the 'apb' tool, or if it would have to go into 'bundle-lib'.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
