### ISSUE TITLE
apb tool should use its own logger

### ISSUE THREAD

**Issue by dymurray** [automationbroker/apb#82]
We have a few logging improvements to make:
* `apb` should be using a separate logger from `bundle-lib`
* `apb` should be logging to disk
* `apb` should provide more customization from a user to print varying verbosity levels from within `apb` and `bundle-lib`

**Comment by jmrodri** [comment]
https://github.com/sirupsen/logrus/issues/673

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
