### ISSUE TITLE
Track deployed APBs parameters locally or within custom resources

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#89]
When users deploy APBs with this tool, we don't currently track created resources. When running any sort of post-provision action, it would be nice to interact with existing objects rather then having to re-specify all params.

If we're not interested in going down the path of complete tracking of deployed objects, a simple approach would be to save off deployed APBs in a local configuration directory and allow users to perform additional actions (bind, deprovision, etc.) from any of the known deployed APBs.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
