### ISSUE TITLE
Add "history" command

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#91]
We could quite easily implement a `history` command that shows the a record of APB actions performed from the tool.

```
$ apb history
# or
$ apb bundle history

|  BUNDLE    |    ACTION    |    NAMESPACE/POD              |   TIMESTAMP
----------------------------------------------------------------------------------
 mysql-apb        provision      foobar/bundle-f8798-[...]    5-12-2018@14:33:32
```

We might also consider including some sort of instance ID (at least for provision actions).  We could then run a `deprovision <instance-id>` and have all of the parameters filled in automatically, assuming they were saved off. 

If we track this kind of info we should be able to allow the user to do an `apb watch !!` type command if they didn't initially specify the follow command and want to watch the last action that was launched.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
