### ISSUE TITLE
Fails to provision APBs that check for "in_cluster"

### ISSUE THREAD

**Issue by djwhatle** [automationbroker/apb#92]
When I try to run against mysql-apb or postgresql-apb, nearly all ansible tasks are skipped because we set the "in_cluster" to false in runner.go.

**Comment by jmrodri** [comment]
Tool has been deprecated for the new Operators model. Please consider using Operator SDK (https://github.com/operator-framework/operator-sdk/) and building an Operator instead of an APB.
