### ISSUE TITLE
Add quay registry type

### ISSUE THREAD

**Issue by vpavlin** [automationbroker/apb#98]
Apparently bundle-lib can handle quay.io registry (https://github.com/automationbroker/bundle-lib/blob/master/registries/registry.go#L234), but the cli reports error when I try to specify it.

Please consider adding quay type.

Currently I workarounded missing type by hand-editing the `registries.json` and puttin `quay` type there. That allowed apb to load bundles from my repository, but generated incorrect image url:

```
"image": "/vpavlin/jupyterhub-apb:latest",
```

After manually fixing that to `quay.io/...` the bundle got successfully deployed.

**Comment by dymurray** [comment]
@vpavlin with PR 101 merged you should be able to type:
```
apb registry add --type quay --org vpavlin quay-registry
```
