### ISSUE TITLE
Make Image Pull Policy configurable

### ISSUE THREAD

**Issue by vpavlin** [automationbroker/apb#99]
By hardcoding ImagePullPolicy to `IfNotPresent`:

https://github.com/automationbroker/apb/blob/56f8fbf94a3b7c2fca7acb6ca630812d3885a7d6/pkg/runner/runner.go#L152

you basically make the bundle non-updateable when OpenShift/Kubernetes place the pod on the same node as previous run.

Please make the ImagePullPolicy configurable in cli so that a user can enforce `Always` value to make sure the bundle image gets pulled when there is a new version with the same tag. Or just switch to `Always` by default as that makes much more sense for this use case

**Comment by dymurray** [comment]
`Always` makes sense in this context since we expect the underlying image to always be changing.
